 Processor with SSE2 support
 MySQL = 5.6 /5.7 (Windows  only/ Linux not support)
 CMake = 3.16.0/3.10.2 (Windows  only/ Linux not support)
 OpenSSL = 1.1.0 (Windows  only/ Linux not support)
 Boost 1.58.0 - 1.65.1 (Windows only)
 MS Visual Studio = 16 (2019) (Windows only)
